builds:
  - id: mariadb-operator
    main: cmd/operator/main.go
    binary: "mariadb-operator_{{ .Version }}_{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: mariactl
    main: cmd/cli/main.go
    binary: "mariactl_{{ .Version }}_{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
